networks:
  caddy:
    name: caddy
    driver: bridge
    external: true

services:
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - "443:443"
      - "80:80"
      - "443:443/udp"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./Caddyfile.private:/etc/caddy/Caddyfile.private
        - ./ssl:/etc/ssl/custom/
        - ./data/data:/data
        - ./data/config:/config
    env_file:
      - ./.env
