services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    command:
      - "--label-enable"
      - "--cleanup"
      - "--interval"
      - "600" # 10 minutes
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
