networks:
    caddy:
        name: caddy
        driver: bridge
        external: true

services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime_kuma
        restart: unless-stopped
        volumes:
            - ./data/app:/app/data
        networks:
            - caddy
        labels:
            caddy: ${CADDY_DOMAIN}
            caddy.reverse_proxy: "* {{upstreams 3001}}"
