networks:
    caddy:
        name: caddy
        driver: bridge
        external: true

services:
    ghost:
        image: ghost:5-alpine
        container_name: ghost
        networks:
            - caddy
        environment:
            database__client: sqlite3
            database__connection__filename: content/data/ghost.db
            NODE_ENV: production
        volumes:
            - ./data:/var/lib/ghost/content

volumes:
    ghost:
