networks:
  caddy:
    name: caddy
    driver: bridge
    external: true

services:
  memos:
    image: neosmemo/memos:0.27
    restart: unless-stopped
    container_name: memos
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./data/app:/var/opt/memos
    networks:
      - caddy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
