server:
    assets-path: /app/assets

auth:
  secret-key: ${SECRET_KEY}
  users:
    admin:
      password: ${ADMIN_PASSWORD}

theme:
    background-color: 240 13 14
    primary-color: 51 33 68
    negative-color: 358 100 68
    contrast-multiplier: 1.2

pages:
    $include: home.yml
