networks:
  glance:
    external: false
  caddy:
    name: caddy
    driver: bridge
    external: true

services:
  glance:
    image: glanceapp/glance:v0.7.7
    container_name: glance
    restart: unless-stopped
    networks:
      - glance
      - caddy
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
